name: Deploy examples
on:
  push:
    branches:
      - main
permissions: 
  contents: write
jobs:
  build-and-deploy:
    # prevents this action from running on forks
    if: github.repository == 'FaberVitale/roma-js-site'
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    env:
      HUSKY: '0'
      PUBLIC_SITE_URL: "https://fabervitale.github.io/roma-js-site"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.15.0'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build

      - name: Post build actions
        run: touch ./dist/.nojekill # Avoids 404 when pathname includes underscores

      - name: Deploy roma-js site 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist
