name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule: 
    - cron: '1 */12 * * *' # "At minute 1 past every 12th hour." (see https://crontab.guru)
jobs:
  trigger-deploy:
    # prevents this action from running on forks
    if: github.repository == 'Roma-JS/roma-js-on-astro'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          ref: 'release'
      - name: Setup environoment
        run: |
          git config user.name 'cronjob-deploy'
          git config user.email 'noreply@romajs.org'       
          export GIT_DEPLOY_DATE="$(date)" GIT_DEPLOY_CID="$(git rev-parse --short HEAD)"
      - name: Update site-deploy.yml
        run: |
          printf 'date: %s\ncid: %s\n' "$GIT_DEPLOY_DATE" "$GIT_DEPLOY_CID" > site-deploy.yml
      - name: Commit and push changes
        run: |
          git add site-deploy.yml
          git commit -m "cronjob deploy 🚀 of $GIT_DEPLOY_CID at $GIT_DEPLOY_DATE"
          git push origin release
